[package]
name = "bin"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[[bin]]
name = "miax-agent"
path = "src/main.rs"

[dependencies]
agent = { path = "../agent" }
chrono = { workspace = true }
clap = { workspace = true }
controller = { path = "../controller" }
env_logger = { workspace = true }
shadow-rs = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
shadow-rs = { workspace = true }
