[workspace]
members = ["agent", "protocol", "controller", "bin"]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
didcomm-rs = "0.7"
k256 = "0.13"
x25519-dalek = "2.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
env_logger = "0.10"
