## ------------------------------
## ベースイメージ
FROM rust:1.83.0-bookworm AS base
ARG CARGO_CHEF_VERSION=0.1.68
ARG SCCACHE_VERSION=0.9.0
ARG MOLD_VERSION=2.35.1

# 開発ツールのインストール
RUN cargo install --locked cargo-chef --version ${CARGO_CHEF_VERSION} && \
    ARCH=$(uname -m) && \
    curl -L -O https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-${ARCH}-unknown-linux-musl.tar.gz && \
    tar xf sccache-* && \
    cp -p sccache-*/sccache /usr/local/bin/ && \
    rm -rf sccache-* && \
    curl -L -O https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-${ARCH}-linux.tar.gz && \
    tar xf mold-* && \
    cp -p mold-*/bin/* /usr/local/bin/ && \
    rm -rf mold-*

ENV RUSTC_WRAPPER=sccache \
    SCCACHE_DIR=/sccache

## ------------------------------
## プランニングステージ
## プロジェクトの依存関係を分析し、ビルド時に必要な情報をレシピに保存
## 依存関係が変更されていない場合のキャッシュを効率的に利用
FROM base AS planner
WORKDIR /app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json　

## ------------------------------
## ビルドステージ
FROM base AS builder
WORKDIR /app
COPY --from=planner /app/recipe.json recipe.json
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=$SCCACHE_DIR,sharing=locked \
    cargo chef cook --recipe-path recipe.json && \
    sccache --show-stats

# プロジェクトのソースコードをカレントディレクトリに上書きコピーしてビルド
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=$SCCACHE_DIR,sharing=locked \
    cargo build && \
    sccache --show-stats

FROM rust:1.83.0-slim-bullseye AS development
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/target target
COPY --from=builder /app .
